[
 {"Emissão", [type: :type, id: "Emissão"]},
 {"Remoção", [type: :type, id: "Remoção"]},
 {"Bunker", [type: :type, id: "Bunker"]},

 {"Energia", [type: :sector, id: 1]},
 {"Agropecuária", [type: :sector, id: 2]},
 {"Resíduos", [type: :sector, id: 5]},
 {"Processos Industriais", [type: :sector, id: 4]},
 {"Mudança de Uso da Terra", [type: :sector, id: 3]},

 {"CO2 (t)", [type: :gas, id: 86]},
 {"CH4 (t)", [type: :gas, id: 87]},
 {"N2O (t)", [type: :gas, id: 88]},
 {"CO2e (t GWP)", [type: :gas, id: 89]},
 {"CO2e (t GTP)", [type: :gas, id: 90]},
 {"CO (t)", [type: :gas, id: 91]},
 {"NOx (t)", [type: :gas, id: 92]},
 {"COVNM (t)", [type: :gas, id: 93]},
 {"CF4 (t)", [type: :gas, id: 94]},
 {"C2F6 (t)", [type: :gas, id: 95]},
 {"SF6 (t)", [type: :gas, id: 96]},
 {"HFC-23 (t)", [type: :gas, id: 97]},
 {"HFC-32 (t)", [type: :gas, id: 98]},
 {"HFC-134a (t)", [type: :gas, id: 99]},
 {"HFC-125 (t)", [type: :gas, id: 100]},
 {"HFC-143a (t)", [type: :gas, id: 101]},
 {"HFC-152a (t)", [type: :gas, id: 102]},

 {"Acre", [type: :territory, id: 1]},
 {"Alagoas", [type: :territory, id: 2]},
 {"Amazonas", [type: :territory, id: 3]},
 {"Amapá", [type: :territory, id: 4]},
 {"Bahia", [type: :territory, id: 5]},
 {"Ceará", [type: :territory, id: 6]},
 {"Distrito Federal", [type: :territory, id: 7]},
 {"Espírito Santo", [type: :territory, id: 8]},
 {"Goiás", [type: :territory, id: 9]},
 {"Maranhão", [type: :territory, id: 10]},
 {"Minas Gerais", [type: :territory, id: 11]},
 {"Mato Grosso do Sul", [type: :territory, id: 12]},
 {"Mato Grosso", [type: :territory, id: 13]},
 {"Pará", [type: :territory, id: 14]},
 {"Paraíba", [type: :territory, id: 15]},
 {"Pernambuco", [type: :territory, id: 16]},
 {"Piauí", [type: :territory, id: 17]},
 {"Paraná", [type: :territory, id: 18]},
 {"Rio de Janeiro", [type: :territory, id: 19]},
 {"Rio Grande do Norte", [type: :territory, id: 20]},
 {"Rondônia", [type: :territory, id: 21]},
 {"Roraima", [type: :territory, id: 22]},
 {"Rio Grande do Sul", [type: :territory, id: 23]},
 {"Santa Catarina", [type: :territory, id: 24]},
 {"Sergipe", [type: :territory, id: 25]},
 {"São Paulo", [type: :territory, id: 26]},
 {"Tocantins", [type: :territory, id: 27]},
 {"Brasil", [type: :territory, id: 28]},
 {"Internacional", [type: :territory, id: 29]},
 {"Não alocado", [type: :territory, id: 30]},

 {"Emissões Fugitivas", [type: :category, id: 972]},
 {"Produção de Combustíveis", [type: :category, id: 973]},
 {"Exploração de Petróleo e Gás Natural", [type: :category, id: 974]},
 {"Petróleo e Gás Natural", [type: :category, id: 975]},
 {"Refino de Petróleo", [type: :category, id: 976]},
 {"Petróleo", [type: :category, id: 977]},
 {"Transporte de Gás Natural", [type: :category, id: 978]},
 {"Gás Natural", [type: :category, id: 979]},
 {"Produção de Carvão Mineral", [type: :category, id: 980]},
 {"Carvão Mineral", [type: :category, id: 981]},
 {"Emissões pela Queima de Combustíveis", [type: :category, id: 982]},
 {"Transportes", [type: :category, id: 983]},
 {"Rodoviário", [type: :category, id: 984]},
 {"Diesel mineral", [type: :category, id: 985]},
 {"Caminhões", [type: :category, id: 986]},
 {"Comerciais Leves", [type: :category, id: 987]},
 {"Ônibus", [type: :category, id: 988]},
 {"Gasolina automotiva", [type: :category, id: 989]},
 {"Automóveis", [type: :category, id: 990]},
 {"Motocicletas", [type: :category, id: 991]},
 {"Gás natural seco", [type: :category, id: 992]},
 {"Industrial", [type: :category, id: 993]},
 {"Têxtil", [type: :category, id: 994]},
 {"Querosene iluminante", [type: :category, id: 995]},
 {"Consumo Final Energético", [type: :category, id: 996]},
 {"Ferro Gusa e Aço", [type: :category, id: 997]},
 {"Alimentos e Bebidas", [type: :category, id: 998]},
 {"Gás canalizado RJ", [type: :category, id: 999]},
 {"Outras Indústrias", [type: :category, id: 1000]},
 {"Carvão vapor 3100", [type: :category, id: 1001]},
 {"Mineração e Pelotização", [type: :category, id: 1002]},
 {"Carvão vapor 4500", [type: :category, id: 1003]},
 {"Gás canalizado SP", [type: :category, id: 1004]},
 {"Cimento", [type: :category, id: 1005]},
 {"NÃO IDENTIFICADO", [type: :category, id: 1006]},
 {"Outros energéticos de petróleo", [type: :category, id: 1007]},
 {"Nafta", [type: :category, id: 1008]},
 {"GLP", [type: :category, id: 1009]},
 {"Carvão vapor 6000", [type: :category, id: 1010]},
 {"Carvão vapor 4200", [type: :category, id: 1011]},
 {"Papel e Celulose", [type: :category, id: 1012]},
 {"Carvão vapor 3300", [type: :category, id: 1013]},
 {"Agropecuário", [type: :category, id: 1014]},
 {"NÃO SE APLICA", [type: :category, id: 1015]},
 {"Cerâmica", [type: :category, id: 1016]},
 {"Residencial", [type: :category, id: 1017]},
 {"Química", [type: :category, id: 1018]},
 {"Carvão vapor 3700", [type: :category, id: 1019]},
 {"Carvão vapor 5200", [type: :category, id: 1020]},
 {"Carvão vapor 4700", [type: :category, id: 1021]},
 {"Não Ferrosos e Outros da Metalurgia", [type: :category, id: 1022]},
 {"Coque de petróleo", [type: :category, id: 1023]},
 {"Óleo combustível", [type: :category, id: 1024]},
 {"Carvão vapor sem especificação", [type: :category, id: 1025]},
 {"Carvão vapor 5900", [type: :category, id: 1026]},
 {"Comercial", [type: :category, id: 1027]},
 {"Público", [type: :category, id: 1028]},
 {"Centrais Elétricas Autoprodutoras", [type: :category, id: 1029]},
 {"Gás de refinaria", [type: :category, id: 1030]},
 {"Coque de carvão mineral", [type: :category, id: 1031]},
 {"Gás natural úmido", [type: :category, id: 1032]},
 {"Ferro Ligas", [type: :category, id: 1033]},
 {"Geração de Eletricidade (Serviço Público)", [type: :category, id: 1034]},
 {"Centrais Elétricas de Serviço Público", [type: :category, id: 1035]},
 {"Outras não renováveis", [type: :category, id: 1036]},
 {"Alcatrão", [type: :category, id: 1037]},
 {"Produção de álcool", [type: :category, id: 1038]},
 {"Ferroviário", [type: :category, id: 1039]},
 {"Locomotivas", [type: :category, id: 1040]},
 {"Hidroviário", [type: :category, id: 1041]},
 {"Embarcações", [type: :category, id: 1042]},
 {"Gás de coqueria", [type: :category, id: 1043]},
 {"Aéreo", [type: :category, id: 1044]},
 {"Querosene de aviação", [type: :category, id: 1045]},
 {"Aeronaves", [type: :category, id: 1046]},
 {"Gasolina de aviação", [type: :category, id: 1047]},
 {"Gasolina C", [type: :category, id: 1048]},
 {"Óleo diesel", [type: :category, id: 1049]},
 {"Álcool hidratado", [type: :category, id: 1050]},
 {"Bagaço de cana", [type: :category, id: 1051]},
 {"Lenha", [type: :category, id: 1052]},
 {"Carvão vegetal", [type: :category, id: 1053]},
 {"Biomassa", [type: :category, id: 1054]},
 {"Outras Renováveis", [type: :category, id: 1055]},
 {"Lixívia", [type: :category, id: 1056]},
 {"Produção de Carvão Vegetal", [type: :category, id: 1057]},
 {"Lenha Carvoejamento", [type: :category, id: 1058]},
 {"Carvoarias", [type: :category, id: 1059]},
 {"Biogás", [type: :category, id: 1060]},
 {"Indústria Química", [type: :category, id: 1061]},
 {"Produção de Amônia", [type: :category, id: 1062]},
 {"Produção de Carbureto de Cálcio", [type: :category, id: 1063]},
 {"Produção de Metanol", [type: :category, id: 1064]},
 {"Produção de Eteno", [type: :category, id: 1065]},
 {"Produção de Cloreto de Vinila", [type: :category, id: 1066]},
 {"Produção de Óxido de Eteno", [type: :category, id: 1067]},
 {"Produção de Acrilonitrila", [type: :category, id: 1068]},
 {"Produção de Negro-de-fumo", [type: :category, id: 1069]},
 {"Produção de Ácido Fosfórico", [type: :category, id: 1070]},
 {"Produção de Coque de Petróleo Calcinado", [type: :category, id: 1071]},
 {"Produção de Ácido Nítrico", [type: :category, id: 1072]},
 {"Produção de Ácido Adípico", [type: :category, id: 1073]},
 {"Produção de Caprolactama", [type: :category, id: 1074]},
 {"Produção de Dicloroetano", [type: :category, id: 1075]},
 {"Produção de ABS", [type: :category, id: 1076]},
 {"Produção de Anidrido Ftálico", [type: :category, id: 1077]},
 {"Produção de Borracha de butadieno estireno (SBR)", [type: :category, id: 1078]},
 {"Produção de Estireno", [type: :category, id: 1079]},
 {"Produção de Etilbenzeno", [type: :category, id: 1080]},
 {"Produção de Formaldeído", [type: :category, id: 1081]},
 {"Produção de PVC", [type: :category, id: 1082]},
 {"Produção de Poliestireno", [type: :category, id: 1083]},
 {"Produção de Polietileno PEAD", [type: :category, id: 1084]},
 {"Produção de Polietileno PEBD", [type: :category, id: 1085]},
 {"Produção de Polietileno PELBD", [type: :category, id: 1086]},
 {"Produção de Polipropileno", [type: :category, id: 1087]},
 {"Produção de Propeno", [type: :category, id: 1088]},
 {"Produtos Minerais", [type: :category, id: 1089]},
 {"Produção de Cimento", [type: :category, id: 1090]},
 {"Produção de Cal", [type: :category, id: 1091]},
 {"Cal Calcítica", [type: :category, id: 1092]},
 {"Cal Dolomítica", [type: :category, id: 1093]},
 {"Cal Magnesiana", [type: :category, id: 1094]},
 {"Produção de Vidro", [type: :category, id: 1095]},
 {"Consumo de Calcário", [type: :category, id: 1096]},
 {"Consumo de Dolomita", [type: :category, id: 1097]},
 {"Consumo de Barrilha", [type: :category, id: 1098]},
 {"Produção de Metais", [type: :category, id: 1099]},
 {"Produção de Ferro Gusa e Aço", [type: :category, id: 1100]},
 {"Consumo de Combustíveis Redutores", [type: :category, id: 1101]},
 {"Consumo de Combustíveis Fósseis", [type: :category, id: 1102]},
 {"Consumo de Combustíveis Renováveis", [type: :category, id: 1103]},
 {"Produção de Ferroligas", [type: :category, id: 1104]},
 {"Produção de Alumínio", [type: :category, id: 1105]},
 {"Tecnologia Soderberg", [type: :category, id: 1106]},
 {"Tecnologia Prebaked Anode", [type: :category, id: 1107]},
 {"Produção de Magnésio", [type: :category, id: 1108]},
 {"Uso de SF6", [type: :category, id: 1109]},
 {"Produção de Outros Não-Ferrosos", [type: :category, id: 1110]},
 {"Emissões de HFCs", [type: :category, id: 1111]},
 {"Equipamentos Elétricos", [type: :category, id: 1112]},
 {"Uso Não-Energético de Combustíveis e Uso de Solventes", [type: :category, id: 1113]},
 {"Consumo Final Não Energético", [type: :category, id: 1114]},
 {"Consumo em Outros Setores", [type: :category, id: 1115]},
 {"Lubrificantes", [type: :category, id: 1116]},
 {"Álcool anidro", [type: :category, id: 1117]},
 {"Outros não energéticos de petróleo", [type: :category, id: 1118]},
 {"Solventes", [type: :category, id: 1119]},
 {"Fermentação Entérica", [type: :category, id: 1120]},
 {"Diretas", [type: :category, id: 1121]},
 {"Outros", [type: :category, id: 1122]},
 {"Animal", [type: :category, id: 1123]},
 {"Gado de Corte", [type: :category, id: 1124]},
 {"Gado de Leite", [type: :category, id: 1125]},
 {"Suínos", [type: :category, id: 1126]},
 {"Ovino", [type: :category, id: 1127]},
 {"Caprino", [type: :category, id: 1128]},
 {"Equino", [type: :category, id: 1129]},
 {"Asinino", [type: :category, id: 1130]},
 {"Muar", [type: :category, id: 1131]},
 {"Bubalino", [type: :category, id: 1132]},
 {"Manejo de Dejetos Animais", [type: :category, id: 1133]},
 {"Aves", [type: :category, id: 1134]},
 {"Cultivo do Arroz", [type: :category, id: 1135]},
 {"Vegetal", [type: :category, id: 1136]},
 {"Arroz", [type: :category, id: 1137]},
 {"Queima de Resíduos Agrícolas", [type: :category, id: 1138]},
 {"Algodão", [type: :category, id: 1139]},
 {"Cana de Açucar", [type: :category, id: 1140]},
 {"Solos Agrícolas", [type: :category, id: 1141]},
 {"Deposição de dejetos em pastagem", [type: :category, id: 1142]},
 {"Fertilizantes Sinteticos", [type: :category, id: 1143]},
 {"Aplicação de resíduos orgânicos", [type: :category, id: 1144]},
 {"Vinhaça", [type: :category, id: 1145]},
 {"Resíduos Agrícolas", [type: :category, id: 1146]},
 {"Soja", [type: :category, id: 1147]},
 {"Feijão", [type: :category, id: 1148]},
 {"Milho", [type: :category, id: 1149]},
 {"Mandioca", [type: :category, id: 1150]},
 {"Outras Culturas", [type: :category, id: 1151]},
 {"Solos orgânicos", [type: :category, id: 1152]},
 {"Indiretas", [type: :category, id: 1153]},
 {"Deposição Atmosférica", [type: :category, id: 1154]},
 {"Lixiviação", [type: :category, id: 1155]},
 {"Tratamento de Efluentes Industriais", [type: :category, id: 1156]},
 {"Leite pasteurizado", [type: :category, id: 1157]},
 {"Leite cru", [type: :category, id: 1158]},
 {"Cervejas", [type: :category, id: 1159]},
 {"Bovinos", [type: :category, id: 1160]},
 {"Alcool", [type: :category, id: 1161]},
 {"Açúcar", [type: :category, id: 1162]},
 {"Disposição de Resíduos", [type: :category, id: 1163]},
 {"Tratamento de Efluentes Domésticos", [type: :category, id: 1164]},
 {"Incineração de Resíduos", [type: :category, id: 1165]},
 {"Calagem", [type: :category, id: 1166]},
 {"Queima de residuos", [type: :category, id: 1167]},
 {"Amazônia", [type: :category, id: 1168]},
 {"Caatinga", [type: :category, id: 1169]},
 {"Cerrado", [type: :category, id: 1170]},
 {"Mata Atlântica", [type: :category, id: 1171]},
 {"Pampa", [type: :category, id: 1172]},
 {"Pantanal", [type: :category, id: 1173]},
 {"Alterações de Uso do Solo", [type: :category, id: 1174]},
 {"Remoções de Áreas Protegidas", [type: :category, id: 1175]},
 {"Unidade de Conservação", [type: :category, id: 1176]},
 {"Terra Indígena", [type: :category, id: 1177]}
]
