[
  {"Emissão", :type, [id: "Emissão"]},
  {"Remoção", :type, [id: "Remoção"]},
  {"Bunker", :type, [id: "Bunker"]},

  {"Energia", :sector, [id: 1]},
  {"Agropecuária", :sector, [id: 2]},
  {"Resíduos", :sector, [id: 5]},
  {"Processos Industriais", :sector, [id: 4]},
  {"Mudança de Uso da Terra", :sector, [id: 3]},

  {"CO2 (t)", :gas, [id: 86]},
  {"CH4 (t)", :gas, [id: 87]},
  {"N2O (t)", :gas, [id: 88]},
  {"CO2e (t GWP)", :gas, [id: 89]},
  {"CO2e (t GTP)", :gas, [id: 90]},
  {"CO (t)", :gas, [id: 91]},
  {"NOx (t)", :gas, [id: 92]},
  {"COVNM (t)", :gas, [id: 93]},
  {"CF4 (t)", :gas, [id: 94]},
  {"C2F6 (t)", :gas, [id: 95]},
  {"SF6 (t)", :gas, [id: 96]},
  {"HFC-23 (t)", :gas, [id: 97]},
  {"HFC-32 (t)", :gas, [id: 98]},
  {"HFC-134a (t)", :gas, [id: 99]},
  {"HFC-125 (t)", :gas, [id: 100]},
  {"HFC-143a (t)", :gas, [id: 101]},
  {"HFC-152a (t)", :gas, [id: 102]},

  {"Acre", :territory, [id: 1]},
  {"Alagoas", :territory, [id: 2]},
  {"Amazonas", :territory, [id: 3]},
  {"Amapá", :territory, [id: 4]},
  {"Bahia", :territory, [id: 5]},
  {"Ceará", :territory, [id: 6]},
  {"Distrito Federal", :territory, [id: 7]},
  {"Espírito Santo", :territory, [id: 8]},
  {"Goiás", :territory, [id: 9]},
  {"Maranhão", :territory, [id: 10]},
  {"Minas Gerais", :territory, [id: 11]},
  {"Mato Grosso do Sul", :territory, [id: 12]},
  {"Mato Grosso", :territory, [id: 13]},
  {"Pará", :territory, [id: 14]},
  {"Paraíba", :territory, [id: 15]},
  {"Pernambuco", :territory, [id: 16]},
  {"Piauí", :territory, [id: 17]},
  {"Paraná", :territory, [id: 18]},
  {"Rio de Janeiro", :territory, [id: 19]},
  {"Rio Grande do Norte", :territory, [id: 20]},
  {"Rondônia", :territory, [id: 21]},
  {"Roraima", :territory, [id: 22]},
  {"Rio Grande do Sul", :territory, [id: 23]},
  {"Santa Catarina", :territory, [id: 24]},
  {"Sergipe", :territory, [id: 25]},
  {"São Paulo", :territory, [id: 26]},
  {"Tocantins", :territory, [id: 27]},
  {"Brasil", :territory, [id: 28]},
  {"Internacional", :territory, [id: 29]},
  {"Não alocado", :territory, [id: 30]},

  {"Emissões Fugitivas", :category, [id: 972]},
  {"Produção de Combustíveis", :category, [id: 973]},
  {"Exploração de Petróleo e Gás Natural", :category, [id: 974]},
  {"Petróleo e Gás Natural", :category, [id: 975]},
  {"Refino de Petróleo", :category, [id: 976]},
  {"Petróleo", :category, [id: 977]},
  {"Transporte de Gás Natural", :category, [id: 978]},
  {"Gás Natural", :category, [id: 979]},
  {"Produção de Carvão Mineral", :category, [id: 980]},
  {"Carvão Mineral", :category, [id: 981]},
  {"Emissões pela Queima de Combustíveis", :category, [id: 982]},
  {"Transportes", :category, [id: 983]},
  {"Rodoviário", :category, [id: 984]},
  {"Diesel mineral", :category, [id: 985]},
  {"Caminhões", :category, [id: 986]},
  {"Comerciais Leves", :category, [id: 987]},
  {"Ônibus", :category, [id: 988]},
  {"Gasolina automotiva", :category, [id: 989]},
  {"Automóveis", :category, [id: 990]},
  {"Motocicletas", :category, [id: 991]},
  {"Gás natural seco", :category, [id: 992]},
  {"Industrial", :category, [id: 993]},
  {"Têxtil", :category, [id: 994]},
  {"Querosene iluminante", :category, [id: 995]},
  {"Consumo Final Energético", :category, [id: 996]},
  {"Ferro Gusa e Aço", :category, [id: 997]},
  {"Alimentos e Bebidas", :category, [id: 998]},
  {"Gás canalizado RJ", :category, [id: 999]},
  {"Outras Indústrias", :category, [id: 1000]},
  {"Carvão vapor 3100", :category, [id: 1001]},
  {"Mineração e Pelotização", :category, [id: 1002]},
  {"Carvão vapor 4500", :category, [id: 1003]},
  {"Gás canalizado SP", :category, [id: 1004]},
  {"Cimento", :category, [id: 1005]},
  {"NÃO IDENTIFICADO", :category, [id: 1006]},
  {"Outros energéticos de petróleo", :category, [id: 1007]},
  {"Nafta", :category, [id: 1008]},
  {"GLP", :category, [id: 1009]},
  {"Carvão vapor 6000", :category, [id: 1010]},
  {"Carvão vapor 4200", :category, [id: 1011]},
  {"Papel e Celulose", :category, [id: 1012]},
  {"Carvão vapor 3300", :category, [id: 1013]},
  {"Agropecuário", :category, [id: 1014]},
  {"NÃO SE APLICA", :category, [id: 1015]},
  {"Cerâmica", :category, [id: 1016]},
  {"Residencial", :category, [id: 1017]},
  {"Química", :category, [id: 1018]},
  {"Carvão vapor 3700", :category, [id: 1019]},
  {"Carvão vapor 5200", :category, [id: 1020]},
  {"Carvão vapor 4700", :category, [id: 1021]},
  {"Não Ferrosos e Outros da Metalurgia", :category, [id: 1022]},
  {"Coque de petróleo", :category, [id: 1023]},
  {"Óleo combustível", :category, [id: 1024]},
  {"Carvão vapor sem especificação", :category, [id: 1025]},
  {"Carvão vapor 5900", :category, [id: 1026]},
  {"Comercial", :category, [id: 1027]},
  {"Público", :category, [id: 1028]},
  {"Centrais Elétricas Autoprodutoras", :category, [id: 1029]},
  {"Gás de refinaria", :category, [id: 1030]},
  {"Coque de carvão mineral", :category, [id: 1031]},
  {"Gás natural úmido", :category, [id: 1032]},
  {"Ferro Ligas", :category, [id: 1033]},
  {"Geração de Eletricidade (Serviço Público)", :category, [id: 1034]},
  {"Centrais Elétricas de Serviço Público", :category, [id: 1035]},
  {"Outras não renováveis", :category, [id: 1036]},
  {"Alcatrão", :category, [id: 1037]},
  {"Produção de álcool", :category, [id: 1038]},
  {"Ferroviário", :category, [id: 1039]},
  {"Locomotivas", :category, [id: 1040]},
  {"Hidroviário", :category, [id: 1041]},
  {"Embarcações", :category, [id: 1042]},
  {"Gás de coqueria", :category, [id: 1043]},
  {"Aéreo", :category, [id: 1044]},
  {"Querosene de aviação", :category, [id: 1045]},
  {"Aeronaves", :category, [id: 1046]},
  {"Gasolina de aviação", :category, [id: 1047]},
  {"Gasolina C", :category, [id: 1048]},
  {"Óleo diesel", :category, [id: 1049]},
  {"Álcool hidratado", :category, [id: 1050]},
  {"Bagaço de cana", :category, [id: 1051]},
  {"Lenha", :category, [id: 1052]},
  {"Carvão vegetal", :category, [id: 1053]},
  {"Biomassa", :category, [id: 1054]},
  {"Outras Renováveis", :category, [id: 1055]},
  {"Lixívia", :category, [id: 1056]},
  {"Produção de Carvão Vegetal", :category, [id: 1057]},
  {"Lenha Carvoejamento", :category, [id: 1058]},
  {"Carvoarias", :category, [id: 1059]},
  {"Biogás", :category, [id: 1060]},
  {"Indústria Química", :category, [id: 1061]},
  {"Produção de Amônia", :category, [id: 1062]},
  {"Produção de Carbureto de Cálcio", :category, [id: 1063]},
  {"Produção de Metanol", :category, [id: 1064]},
  {"Produção de Eteno", :category, [id: 1065]},
  {"Produção de Cloreto de Vinila", :category, [id: 1066]},
  {"Produção de Óxido de Eteno", :category, [id: 1067]},
  {"Produção de Acrilonitrila", :category, [id: 1068]},
  {"Produção de Negro-de-fumo", :category, [id: 1069]},
  {"Produção de Ácido Fosfórico", :category, [id: 1070]},
  {"Produção de Coque de Petróleo Calcinado", :category, [id: 1071]},
  {"Produção de Ácido Nítrico", :category, [id: 1072]},
  {"Produção de Ácido Adípico", :category, [id: 1073]},
  {"Produção de Caprolactama", :category, [id: 1074]},
  {"Produção de Dicloroetano", :category, [id: 1075]},
  {"Produção de ABS", :category, [id: 1076]},
  {"Produção de Anidrido Ftálico", :category, [id: 1077]},
  {"Produção de Borracha de butadieno estireno (SBR)", :category, [id: 1078]},
  {"Produção de Estireno", :category, [id: 1079]},
  {"Produção de Etilbenzeno", :category, [id: 1080]},
  {"Produção de Formaldeído", :category, [id: 1081]},
  {"Produção de PVC", :category, [id: 1082]},
  {"Produção de Poliestireno", :category, [id: 1083]},
  {"Produção de Polietileno PEAD", :category, [id: 1084]},
  {"Produção de Polietileno PEBD", :category, [id: 1085]},
  {"Produção de Polietileno PELBD", :category, [id: 1086]},
  {"Produção de Polipropileno", :category, [id: 1087]},
  {"Produção de Propeno", :category, [id: 1088]},
  {"Produtos Minerais", :category, [id: 1089]},
  {"Produção de Cimento", :category, [id: 1090]},
  {"Produção de Cal", :category, [id: 1091]},
  {"Cal Calcítica", :category, [id: 1092]},
  {"Cal Dolomítica", :category, [id: 1093]},
  {"Cal Magnesiana", :category, [id: 1094]},
  {"Produção de Vidro", :category, [id: 1095]},
  {"Consumo de Calcário", :category, [id: 1096]},
  {"Consumo de Dolomita", :category, [id: 1097]},
  {"Consumo de Barrilha", :category, [id: 1098]},
  {"Produção de Metais", :category, [id: 1099]},
  {"Produção de Ferro Gusa e Aço", :category, [id: 1100]},
  {"Consumo de Combustíveis Redutores", :category, [id: 1101]},
  {"Consumo de Combustíveis Fósseis", :category, [id: 1102]},
  {"Consumo de Combustíveis Renováveis", :category, [id: 1103]},
  {"Produção de Ferroligas", :category, [id: 1104]},
  {"Produção de Alumínio", :category, [id: 1105]},
  {"Tecnologia Soderberg", :category, [id: 1106]},
  {"Tecnologia Prebaked Anode", :category, [id: 1107]},
  {"Produção de Magnésio", :category, [id: 1108]},
  {"Uso de SF6", :category, [id: 1109]},
  {"Produção de Outros Não-Ferrosos", :category, [id: 1110]},
  {"Emissões de HFCs", :category, [id: 1111]},
  {"Equipamentos Elétricos", :category, [id: 1112]},
  {"Uso Não-Energético de Combustíveis e Uso de Solventes", :category, [id: 1113]},
  {"Consumo Final Não Energético", :category, [id: 1114]},
  {"Consumo em Outros Setores", :category, [id: 1115]},
  {"Lubrificantes", :category, [id: 1116]},
  {"Álcool anidro", :category, [id: 1117]},
  {"Outros não energéticos de petróleo", :category, [id: 1118]},
  {"Solventes", :category, [id: 1119]},
  {"Fermentação Entérica", :category, [id: 1120]},
  {"Diretas", :category, [id: 1121]},
  {"Outros", :category, [id: 1122]},
  {"Animal", :category, [id: 1123]},
  {"Gado de Corte", :category, [id: 1124]},
  {"Gado de Leite", :category, [id: 1125]},
  {"Suínos", :category, [id: 1126]},
  {"Ovino", :category, [id: 1127]},
  {"Caprino", :category, [id: 1128]},
  {"Equino", :category, [id: 1129]},
  {"Asinino", :category, [id: 1130]},
  {"Muar", :category, [id: 1131]},
  {"Bubalino", :category, [id: 1132]},
  {"Manejo de Dejetos Animais", :category, [id: 1133]},
  {"Aves", :category, [id: 1134]},
  {"Cultivo do Arroz", :category, [id: 1135]},
  {"Vegetal", :category, [id: 1136]},
  {"Arroz", :category, [id: 1137]},
  {"Queima de Resíduos Agrícolas", :category, [id: 1138]},
  {"Algodão", :category, [id: 1139]},
  {"Cana de Açucar", :category, [id: 1140]},
  {"Solos Agrícolas", :category, [id: 1141]},
  {"Deposição de dejetos em pastagem", :category, [id: 1142]},
  {"Fertilizantes Sinteticos", :category, [id: 1143]},
  {"Aplicação de resíduos orgânicos", :category, [id: 1144]},
  {"Vinhaça", :category, [id: 1145]},
  {"Resíduos Agrícolas", :category, [id: 1146]},
  {"Soja", :category, [id: 1147]},
  {"Feijão", :category, [id: 1148]},
  {"Milho", :category, [id: 1149]},
  {"Mandioca", :category, [id: 1150]},
  {"Outras Culturas", :category, [id: 1151]},
  {"Solos orgânicos", :category, [id: 1152]},
  {"Indiretas", :category, [id: 1153]},
  {"Deposição Atmosférica", :category, [id: 1154]},
  {"Lixiviação", :category, [id: 1155]},
  {"Tratamento de Efluentes Industriais", :category, [id: 1156]},
  {"Leite pasteurizado", :category, [id: 1157]},
  {"Leite cru", :category, [id: 1158]},
  {"Cervejas", :category, [id: 1159]},
  {"Bovinos", :category, [id: 1160]},
  {"Alcool", :category, [id: 1161]},
  {"Açúcar", :category, [id: 1162]},
  {"Disposição de Resíduos", :category, [id: 1163]},
  {"Tratamento de Efluentes Domésticos", :category, [id: 1164]},
  {"Incineração de Resíduos", :category, [id: 1165]},
  {"Calagem", :category, [id: 1166]},
  {"Queima de residuos", :category, [id: 1167]},
  {"Amazônia", :category, [id: 1168]},
  {"Caatinga", :category, [id: 1169]},
  {"Cerrado", :category, [id: 1170]},
  {"Mata Atlântica", :category, [id: 1171]},
  {"Pampa", :category, [id: 1172]},
  {"Pantanal", :category, [id: 1173]},
  {"Alterações de Uso do Solo", :category, [id: 1174]},
  {"Remoções de Áreas Protegidas", :category, [id: 1175]},
  {"Unidade de Conservação", :category, [id: 1176]},
  {"Terra Indígena", :category, [id: 1177]}
]
